import React, { useState, useRef } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { UploadCloud, ScanLine, AlertTriangle, CheckCircle2, ChevronRight, Sparkles, ArrowRight, Download } from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { cn } from '@/lib/utils';
import { chatAPI } from '@/lib/api';
import jsPDF from 'jspdf';
import html2canvas from 'html2canvas';

export default function SkinAnalysis() {
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [showResults, setShowResults] = useState(false);
  const [selectedImage, setSelectedImage] = useState<File | null>(null);
  const [previewUrl, setPreviewUrl] = useState<string | null>(null);
  const [analysisResult, setAnalysisResult] = useState<string | null>(null);
  const [error, setError] = useState<string | null>(null);
  const fileInputRef = useRef<HTMLInputElement>(null);

  const generatePDF = async () => {
    if (!analysisResult) {
      setError('No analysis result to save');
      return;
    }

    try {
      console.log('Starting PDF generation...');
      
      // Create PDF directly with text
      const pdf = new jsPDF('p', 'mm', 'a4');
      const pageWidth = 210;
      const pageHeight = 297;
      const margin = 20;
      const lineHeight = 7;
      let yPosition = margin;
      
      // Add title
      pdf.setFontSize(20);
      pdf.setFont('helvetica', 'bold');
      pdf.text('DermaVerse AI Skin Analysis Report', pageWidth / 2, yPosition, { align: 'center' });
      yPosition += lineHeight * 2;
      
      // Add date
      pdf.setFontSize(12);
      pdf.setFont('helvetica', 'normal');
      pdf.text(`Generated on ${new Date().toLocaleDateString()}`, pageWidth / 2, yPosition, { align: 'center' });
      yPosition += lineHeight * 3;
      
      // Add analysis results header
      pdf.setFontSize(16);
      pdf.setFont('helvetica', 'bold');
      pdf.text('Analysis Results', margin, yPosition);
      yPosition += lineHeight * 2;
      
      // Add analysis content
      pdf.setFontSize(10);
      pdf.setFont('helvetica', 'normal');
      
      // Split text into lines that fit the page width
      const textWidth = pageWidth - (margin * 2);
      const lines = pdf.splitTextToSize(analysisResult, textWidth);
      
      for (let i = 0; i < lines.length; i++) {
        if (yPosition > pageHeight - margin) {
          pdf.addPage();
          yPosition = margin;
        }
        pdf.text(lines[i], margin, yPosition);
        yPosition += lineHeight;
      }
      
      // Add disclaimer
      yPosition += lineHeight * 2;
      if (yPosition > pageHeight - margin - 30) {
        pdf.addPage();
        yPosition = margin;
      }
      
      pdf.setFontSize(8);
      pdf.setFont('helvetica', 'italic');
      const disclaimer = 'This report is generated by DermaVerse AI and is for informational purposes only. Please consult with a qualified dermatologist for professional medical advice.';
      const disclaimerLines = pdf.splitTextToSize(disclaimer, textWidth);
      
      for (let i = 0; i < disclaimerLines.length; i++) {
        pdf.text(disclaimerLines[i], margin, yPosition);
        yPosition += lineHeight;
      }
      
      // Download the PDF
      const fileName = `DermaVerse_Analysis_Report_${new Date().toISOString().split('T')[0]}.pdf`;
      console.log('Saving PDF as:', fileName);
      pdf.save(fileName);
      
      console.log('PDF generation completed');
      
    } catch (error) {
      console.error('Error generating PDF:', error);
      setError('Failed to generate PDF. Please try again.');
    }
  };

  const handleImageSelect = (file: File) => {
    if (!file.type.startsWith('image/')) {
      setError('Please select an image file');
      return;
    }
    
    setSelectedImage(file);
    setError(null);
    
    // Create preview
    const reader = new FileReader();
    reader.onload = (e) => {
      setPreviewUrl(e.target?.result as string);
    };
    reader.readAsDataURL(file);
  };

  const handleDragOver = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    const files = e.dataTransfer.files;
    if (files.length > 0) {
      handleImageSelect(files[0]);
    }
  };

  const handleAnalyze = async () => {
    if (!selectedImage) {
      setError('Please select an image first');
      return;
    }

    setIsAnalyzing(true);
    setError(null);

    try {
      // Send image directly to Gemini API (no disk save)
      const response = await chatAPI.analyzeSkinImage(selectedImage);

      if (response.status === 'success') {
        setAnalysisResult(response.analysis);
        setShowResults(true);
      }
    } catch (err: any) {
      console.error('Analysis error:', err);
      setError(err.response?.data?.message || 'Failed to analyze image. Please try again.');
    } finally {
      setIsAnalyzing(false);
    }
  };

  const handleRetake = () => {
    setShowResults(false);
    setSelectedImage(null);
    setPreviewUrl(null);
    setAnalysisResult(null);
  };

  return (
    <div className="space-y-10 pb-12">
      <div>
        <h1 className="text-5xl font-serif text-[#2C2A25] leading-tight">Clinical Analysis</h1>
        <p className="text-[#5A6B5D] mt-2 text-lg font-light">Upload a clear photo to initiate the neural vision scan.</p>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-10">
        {/* Left Column - Upload Area */}
        <Card className="border-none shadow-xl shadow-[#2C2A25]/5 h-fit bg-white overflow-hidden">
          <CardHeader className="border-b border-[#EDE8E0]/50 pb-6">
            <CardTitle className="text-xl font-serif text-[#2C2A25]">Image Capture</CardTitle>
          </CardHeader>
          <CardContent className="p-8">
            <div 
              className="border-2 border-dashed border-[#EDE8E0] rounded-[3rem] bg-[#FDFBF7] p-12 flex flex-col items-center justify-center text-center transition-all duration-500 hover:border-[#D97757]/50 hover:bg-[#F4EBE6]/50 cursor-pointer group relative overflow-hidden h-[450px]"
              onDragOver={handleDragOver}
              onDrop={handleDrop}
              onClick={() => fileInputRef.current?.click()}
            >
              <input
                ref={fileInputRef}
                type="file"
                accept="image/*"
                onChange={(e) => e.target.files && handleImageSelect(e.target.files[0])}
                className="hidden"
              />
              
              {!isAnalyzing && !showResults && (
                <>
                  {previewUrl ? (
                    <>
                      <img src={previewUrl} alt="Preview" className="w-full h-full object-cover rounded-[2.5rem]" />
                      <div className="absolute inset-0 bg-black/40 flex flex-col items-center justify-center rounded-[2.5rem] opacity-0 hover:opacity-100 transition-opacity">
                        <Button 
                          onClick={(e) => { e.stopPropagation(); handleAnalyze(); }} 
                          className="bg-[#D97757] text-white rounded-full px-10 h-14 text-base hover:bg-[#C86647] shadow-xl"
                        >
                          <ScanLine className="w-5 h-5 mr-3" /> Analyze Now
                        </Button>
                      </div>
                    </>
                  ) : (
                    <>
                      <div className="w-24 h-24 rounded-full bg-white shadow-sm border border-[#EDE8E0] flex items-center justify-center mb-8 group-hover:bg-[#F4EBE6] group-hover:border-[#D97757]/30 transition-colors relative z-10">
                        <UploadCloud className="w-10 h-10 text-[#5A6B5D] group-hover:text-[#D97757] transition-colors" />
                      </div>
                      <h3 className="text-2xl font-serif text-[#2C2A25] mb-3 relative z-10">Click or drag image here</h3>
                      <p className="text-[#5A6B5D] max-w-sm mx-auto mb-10 font-light relative z-10">
                        Ensure good lighting, no makeup, and a neutral expression for best AI accuracy.
                      </p>
                      {error && <p className="text-[#D97757] text-sm mb-6 relative z-10">{error}</p>}
                    </>
                  )}
                </>
              )}

              {isAnalyzing && (
                <div className="absolute inset-0 bg-[#2C2A25] flex flex-col items-center justify-center text-[#FDFBF7] p-8 z-20">
                  <div className="absolute inset-0 bg-noise opacity-20 mix-blend-overlay" />
                  <div className="relative w-72 h-72 rounded-full overflow-hidden mb-10 border-4 border-[#5A6B5D]/30 shadow-2xl">
                    {previewUrl && <img src={previewUrl} alt="Scanning" className="w-full h-full object-cover opacity-60 grayscale" />}
                    
                    {/* Organic Scanning Glow */}
                    <motion.div 
                      className="absolute top-0 left-0 w-full h-full bg-gradient-to-b from-transparent via-[#D97757]/40 to-transparent blur-xl mix-blend-overlay"
                      animate={{ top: ['-100%', '100%', '-100%'] }}
                      transition={{ duration: 3, repeat: Infinity, ease: "easeInOut" }}
                    />
                    
                    {/* Fake bounding boxes */}
                    <motion.div className="absolute top-1/4 left-1/4 w-16 h-16 border border-[#D97757] rounded-full" initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: [0, 1, 0], scale: [0.8, 1.2, 0.8] }} transition={{ duration: 2, repeat: Infinity, delay: 0.5 }} />
                    <motion.div className="absolute bottom-1/3 right-1/4 w-12 h-12 border border-[#5A6B5D] rounded-full" initial={{ opacity: 0, scale: 0.8 }} animate={{ opacity: [0, 1, 0], scale: [0.8, 1.2, 0.8] }} transition={{ duration: 2, repeat: Infinity, delay: 1 }} />
                  </div>
                  <div className="flex items-center gap-4 text-xl font-serif italic text-[#EDE8E0]">
                    <Sparkles className="w-6 h-6 animate-pulse text-[#D97757]" />
                    Analyzing your skin Pookie,please wait...
                  </div>
                </div>
              )}

              {showResults && (
                <div className="absolute inset-0 bg-[#2C2A25] p-4 z-20">
                  <div className="absolute inset-0 bg-noise opacity-20 mix-blend-overlay" />
                  <div className="w-full h-full rounded-[2.5rem] overflow-hidden relative border border-[#5A6B5D]/30 shadow-2xl">
                    {previewUrl && <img src={previewUrl} alt="Result" className="w-full h-full object-cover opacity-90" />}
                    
                    <div className="absolute bottom-6 left-6 right-6 flex justify-between items-center">
                      <Button 
                        variant="outline" 
                        className="bg-[#2C2A25]/80 border-white/20 text-white hover:bg-[#1A1916] backdrop-blur-md rounded-full px-8 h-12" 
                        onClick={handleRetake}
                      >
                        Retake
                      </Button>
                      <div className="bg-[#5A6B5D]/90 text-white px-6 py-3 rounded-full font-medium text-sm backdrop-blur-md flex items-center gap-3 border border-white/20 shadow-xl">
                        <CheckCircle2 className="w-5 h-5 text-[#EDE8E0]" /> Scan Complete
                      </div>
                    </div>
                  </div>
                </div>
              )}
            </div>
          </CardContent>
        </Card>

        {/* Right Column - Results */}
        <div className="space-y-6">
          <AnimatePresence mode="wait">
            {!showResults ? (
              <motion.div 
                key="empty"
                initial={{ opacity: 0 }}
                animate={{ opacity: 1 }}
                exit={{ opacity: 0 }}
                className="h-full flex flex-col items-center justify-center text-center p-16 border border-[#EDE8E0] border-dashed rounded-[3rem] bg-white/50"
              >
                <div className="w-20 h-20 rounded-full bg-[#FDFBF7] border border-[#EDE8E0] flex items-center justify-center mb-6 shadow-sm">
                  <Sparkles className="w-8 h-8 text-[#5A6B5D]/30" />
                </div>
                <h3 className="text-2xl font-serif text-[#2C2A25] mb-3">Awaiting Image</h3>
                <p className="text-[#5A6B5D] text-base font-light max-w-xs leading-relaxed">Upload an image to see your detailed clinical analysis and personalized recommendations.</p>
              </motion.div>
            ) : (
              <motion.div
                key="results"
                initial={{ opacity: 0, y: 30 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.8, ease: [0.16, 1, 0.3, 1] }}
                className="space-y-6"
              >
                {/* Analysis Result */}
                <Card className="border-none shadow-xl bg-white">
                  <CardHeader className="pb-4 border-b border-[#EDE8E0]/50">
                    <CardTitle className="text-xl font-serif text-[#2C2A25]">AI Clinical Analysis</CardTitle>
                  </CardHeader>
                  <CardContent className="pt-6">
                    <div className="prose prose-sm max-w-none text-[#2C2A25] font-light whitespace-pre-wrap max-h-96 overflow-y-auto">
                      {analysisResult}
                    </div>
                  </CardContent>
                </Card>

                <Button 
                  onClick={generatePDF}
                  className="w-full bg-[#2C2A25] hover:bg-[#1A1916] text-white rounded-full h-14 text-base shadow-xl"
                >
                  <Download className="w-5 h-5 mr-3" />
                  Save Report as PDF
                </Button>
              </motion.div>
            )}
          </AnimatePresence>
        </div>
      </div>
    </div>
  );
}
